# Chi-Square Test

# 1. State the Hypotheses:

In [9]:
import numpy as np
from scipy import stats

In [27]:
#observed_data
obs_data = np.array([
    [50, 70],  # Very Satisfied
    [80, 100], # Satisfied
    [60, 90],  # Neutral
    [30, 50],  # Unsatisfied
    [20, 50]   # Very Unsatisfied
])

In [29]:
row_totl= np.sum(obs_data, axis=1)
row_totl

array([120, 180, 150,  80,  70])

In [31]:
column_totl = np.sum(obs_data, axis=0)
column_totl 

array([240, 360])

In [33]:
grand_totl = np.sum(obs_data)
grand_totl


600

In [35]:
exp_data = np.outer(row_totl, column_totl) / grand_totl

In [37]:
exp_data

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [39]:
120*240

28800

In [41]:
28800/600

48.0

# 2. Compute the Chi-Square Statistic:

In [51]:
chi_stats = np.sum(((obs_data - exp_data)**2) / exp_data)
chi_stats 

Power_divergenceResult(statistic=array([3.38293651, 2.25529101]), pvalue=array([0.4958998 , 0.68892041]))

# 3. Determine the Critical Value:

In [47]:
df=4

In [49]:
chi_critical=stats.chi2.ppf(0.95,4)
chi_critical

9.487729036781154

# 4. Make a Decision: